---
- hosts: all
  gather_facts: false

  tasks:
    - name: Create a VM
      steampunk.aws.ec2_instance:
        name: "{{ i_name }}"
        type: "{{ i_type }}"
        ami: ami-0cff7528ff583bf9a
        key_pair: newkey_NV
        subnet: "{{ i_subnet }}"
